---
- name: Ensure cluster group membership
  fail: msg="Cluster hosts must be members of a group"
  when: pacemaker_ansible_group is not iterable

- name: Install Pacemaker Configuration System package
  yum: name={{ pacemaker_package }} state=installed

- name: Enable and start PCS daemon
  service: name=pcsd enabled=yes state=started

- name: Ensure the password for the cluster user
  user:
    name={{ pacemaker_user }}
    password={{ pacemaker_password | password_hash('sha512', ansible_hostname) }}

- name: Authenticate all nodes
  command: >
    pcs cluster auth
    {% for host in groups[pacemaker_ansible_group] %}
    {{ hostvars[host]['ansible_hostname'] }}
    {% endfor %}
    -u {{ pacemaker_user }} -p {{ pacemaker_password }}
  run_once: true
  args:
    creates: /var/lib/pcsd/tokens

- name: Setup cluster message bus
  run_once: true
  command: >
    pcs cluster setup --name {{ pacemaker_cluster_name }}
    {% for host in groups[pacemaker_ansible_group] %}
    {{ hostvars[host]['ansible_hostname'] }}
    {% endfor %}
  args:
    creates: /etc/corosync/corosync.conf

- name: Start all cluster nodes
  service: name={{ item }} enabled=yes state=started
  with_items:
    - corosync
    - pacemaker

- name: Set cluster properties
  command: pcs property set {{ item.key | replace('_', '-') }}={{ item.value }}
  with_dict: "{{ pacemaker_properties }}"
  when: pacemaker_properties is defined
