---
- debug: var=pacemaker_members

- name: Install Pacemaker Configuration System package
  delegate_to: "{{ pacemaker_members }}"
  yum: name={{ pacemaker_package }} state=installed

- name: Enable and start Pacemaker services
  delegate_to: "{{ pacemaker_members }}"
  service: name={{ item }} enabled=yes state=started
  with_items: "{{ pacemaker_services }}"

- name: Change password for the cluster user
  delegate_to: "{{ pacemaker_members }}"
  user:
    name={{ pacemaker_user }}
    password={{ pacemaker_crypt_password }}

- name: Authenticate all nodes
  delegate_to: "{{ pacemaker_members[0] }}"
  run_once: true
  command: >
    pcs cluster auth
    {% for host in pacemaker_members %}
    {{ hostvars[host]['ansible_hostname'] }}
    {% endfor %}
    -u {{ pacemaker_user }} -p {{ pacemaker_password }}

- name: Setup cluster
  delegate_to: "{{ pacemaker_members[0] }}"
  run_once: true
  command: >
    pcs cluster setup --name {{ pacemaker_cluster_name }}
    {% for host in pacemaker_members %}
    {{ hostvars[host]['ansible_hostname'] }}
    {% endfor %}
